name: Merge Upstream
on:
  schedule:
    # scheduled for every night at midnight
    - cron: '0 0 * * *'

jobs:
  merge-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge upstream branch into local.
        run: |
          git remote add -f upstream "https://github.com/lnls-sirius/lnls-ansible.git"
          git remote -v
          git branch --all
          git config --list
          git checkout --track origin/master
          git merge --ff-only upstream/master
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge master branch into travis-build for triggering CI.
        run: |
          git branch --all
          git config --list
          git checkout --track origin/travis-build
          git merge --no-ff origin/master
          git push origin travis-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
